---
language: node_js
env:
  EXPO_CLI_PASSWORD: REY3grk9gtg@axf.bdj
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo login --non-interactive -u drxxmn
        - npx expo publish --non-interactive

